version: "3"

services:
  web:
    container_name: replicar
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URI: ${MONGO_URI}
        BASE_PATH: ${BASE_PATH}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HOST: ${HOST}
      BASE_PATH: ${BASE_PATH}
      TOKEN: ${TOKEN}
      MONGO_URI: ${MONGO_URI}
      STRIPE_KEY: ${STRIPE_KEY}
