apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-cart-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tylerpitcher/shopping-cart.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true