apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: tylerpitcher/shopping-cart:a2be9fe
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: "https://www.tylerpitcher.com/replicar"
        - name: BASE_PATH
          value: "/replicar"
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: shopping-cart-secret
              key: TOKEN
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: shopping-cart-secret
              key: MONGO_URI
        - name: STRIPE_KEY
          valueFrom:
            secretKeyRef:
              name: shopping-cart-secret
              key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shopping-cart-ingress-https
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && PathPrefix(`/replicar`)
    kind: Rule
    services:
    - name: shopping-cart-service
      port: 3000
  tls:
    secretName: tls-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shopping-cart-ingress-http
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && PathPrefix(`/replicar`)
    kind: Rule
    services:
    - name: shopping-cart-service
      port: 80
    middlewares:
    - name: https-redirect
